/**
 * WhatsApp Device Pairing System for Watsy-Chatbot Platform
 * 
 * This module handles WhatsApp device pairing using QR codes and pairing codes.
 * It provides secure session initialization, device registration, and pairing
 * timeout management with comprehensive error handling.
 */

import QRCode from 'qrcode'
import { v4 as uuidv4 } from 'uuid'
import { prisma } from '@/lib/prisma'
import { WhatsAppService } from './service'
import { 
  DevicePairingData, 
  WhatsAppDevice, 
  WhatsAppServiceError,
  DeviceNotFoundError 
} from './types'
import { WhatsAppDeviceStatus } from '@/generated/prisma'

// ============================================================================
// PAIRING CONFIGURATION
// ============================================================================

interface PairingConfig {
  qrCodeExpirationMinutes: number
  pairingCodeExpirationMinutes: number
  maxPairingAttempts: number
  pairingTimeoutMs: number
  qrCodeSize: number
  qrCodeErrorCorrectionLevel: 'L' | 'M' | 'Q' | 'H'
}

const DEFAULT_PAIRING_CONFIG: PairingConfig = {
  qrCodeExpirationMinutes: 5,
  pairingCodeExpirationMinutes: 10,
  maxPairingAttempts: 3,
  pairingTimeoutMs: 300000, // 5 minutes
  qrCodeSize: 256,
  qrCodeErrorCorrectionLevel: 'M'
}

// ============================================================================
// PAIRING MANAGER CLASS
// ============================================================================

export class DevicePairingManager {
  private whatsappService: WhatsAppService
  private config: PairingConfig
  private activePairingSessions: Map<string, NodeJS.Timeout> = new Map()

  constructor(whatsappService: WhatsAppService, config: Partial<PairingConfig> = {}) {
    this.whatsappService = whatsappService
    this.config = { ...DEFAULT_PAIRING_CONFIG, ...config }
  }

  // ============================================================================
  // QR CODE PAIRING
  // ============================================================================

  /**
   * Generate QR code for device pairing
   */
  async generateQRCode(deviceId: string): Promise<DevicePairingData> {
    try {
      // Verify device exists and belongs to user
      const device = await this.getDeviceWithValidation(deviceId)
      
      // Check if device is in valid state for pairing
      if (device.status === WhatsAppDeviceStatus.CONNECTED) {
        throw new WhatsAppServiceError(
          'Device is already connected',
          'DEVICE_ALREADY_CONNECTED',
          deviceId
        )
      }

      // Clear any existing pairing session
      await this.clearPairingSession(deviceId)

      // Start connection process to get QR code
      const connectionResult = await this.whatsappService.connectDevice(deviceId)
      
      if (!connectionResult.success) {
        throw new WhatsAppServiceError(
          connectionResult.error || 'Failed to start pairing process',
          'PAIRING_FAILED',
          deviceId
        )
      }

      // Wait for QR code generation
      const qrCodeData = await this.waitForQRCode(deviceId)
      
      if (!qrCodeData) {
        throw new WhatsAppServiceError(
          'QR code generation timeout',
          'QR_CODE_TIMEOUT',
          deviceId
        )
      }

      const expiresAt = new Date(Date.now() + this.config.qrCodeExpirationMinutes * 60 * 1000)

      // Set up pairing timeout
      this.setupPairingTimeout(deviceId)

      return {
        qrCode: qrCodeData,
        expiresAt,
        isExpired: false
      }

    } catch (error) {
      await this.handlePairingError(deviceId, error)
      throw error
    }
  }

  /**
   * Wait for QR code to be generated by Baileys
   */
  private async waitForQRCode(deviceId: string, timeoutMs: number = 30000): Promise<string | null> {
    return new Promise((resolve) => {
      const timeout = setTimeout(() => {
        this.whatsappService.removeListener('connection', handler)
        resolve(null)
      }, timeoutMs)

      const handler = (event: any) => {
        if (event.deviceId === deviceId && event.data.qrCode) {
          clearTimeout(timeout)
          this.whatsappService.removeListener('connection', handler)
          resolve(event.data.qrCode)
        }
      }

      this.whatsappService.on('connection', handler)
    })
  }

  // ============================================================================
  // PAIRING CODE ALTERNATIVE
  // ============================================================================

  /**
   * Generate pairing code for devices that cannot scan QR codes
   */
  async generatePairingCode(deviceId: string, phoneNumber: string): Promise<DevicePairingData> {
    try {
      // Verify device exists
      const device = await this.getDeviceWithValidation(deviceId)
      
      // Validate phone number format
      const cleanPhoneNumber = this.validateAndCleanPhoneNumber(phoneNumber)
      
      // Generate secure pairing code
      const pairingCode = this.generateSecurePairingCode()
      const expiresAt = new Date(Date.now() + this.config.pairingCodeExpirationMinutes * 60 * 1000)

      // Store pairing code in database
      await prisma.whatsAppDevice.update({
        where: { id: deviceId },
        data: {
          phoneNumber: cleanPhoneNumber,
          qrCode: pairingCode, // Reusing qrCode field for pairing code
          qrCodeExpires: expiresAt,
          status: WhatsAppDeviceStatus.CONNECTING
        }
      })

      // Set up pairing timeout
      this.setupPairingTimeout(deviceId)

      return {
        pairingCode,
        expiresAt,
        isExpired: false
      }

    } catch (error) {
      await this.handlePairingError(deviceId, error)
      throw error
    }
  }

  /**
   * Validate pairing code entered by user
   */
  async validatePairingCode(deviceId: string, enteredCode: string): Promise<boolean> {
    try {
      const device = await prisma.whatsAppDevice.findUnique({
        where: { id: deviceId },
        select: { qrCode: true, qrCodeExpires: true, status: true }
      })

      if (!device) {
        throw new DeviceNotFoundError(deviceId)
      }

      // Check if pairing code exists and hasn't expired
      if (!device.qrCode || !device.qrCodeExpires) {
        return false
      }

      if (new Date() > device.qrCodeExpires) {
        await this.clearPairingSession(deviceId)
        return false
      }

      // Validate code
      const isValid = device.qrCode === enteredCode.trim().toUpperCase()
      
      if (isValid) {
        // Start connection process
        await this.whatsappService.connectDevice(deviceId)
      }

      return isValid

    } catch (error) {
      console.error(`Failed to validate pairing code for device ${deviceId}:`, error)
      return false
    }
  }

  // ============================================================================
  // SESSION MANAGEMENT
  // ============================================================================

  /**
   * Check pairing status
   */
  async getPairingStatus(deviceId: string): Promise<{
    status: WhatsAppDeviceStatus
    qrCode?: string
    pairingCode?: string
    expiresAt?: Date
    isExpired: boolean
  }> {
    const device = await prisma.whatsAppDevice.findUnique({
      where: { id: deviceId },
      select: {
        status: true,
        qrCode: true,
        qrCodeExpires: true
      }
    })

    if (!device) {
      throw new DeviceNotFoundError(deviceId)
    }

    const now = new Date()
    const isExpired = device.qrCodeExpires ? now > device.qrCodeExpires : false

    return {
      status: device.status,
      qrCode: device.qrCode || undefined,
      pairingCode: device.qrCode || undefined, // Same field used for both
      expiresAt: device.qrCodeExpires || undefined,
      isExpired
    }
  }

  /**
   * Cancel pairing process
   */
  async cancelPairing(deviceId: string): Promise<boolean> {
    try {
      await this.clearPairingSession(deviceId)
      await this.whatsappService.disconnectDevice(deviceId)
      
      await prisma.whatsAppDevice.update({
        where: { id: deviceId },
        data: {
          status: WhatsAppDeviceStatus.DISCONNECTED,
          qrCode: null,
          qrCodeExpires: null
        }
      })

      return true

    } catch (error) {
      console.error(`Failed to cancel pairing for device ${deviceId}:`, error)
      return false
    }
  }

  /**
   * Refresh pairing session (generate new QR/pairing code)
   */
  async refreshPairingSession(deviceId: string): Promise<DevicePairingData> {
    try {
      // Cancel current session
      await this.cancelPairing(deviceId)
      
      // Wait a moment for cleanup
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      // Generate new QR code
      return await this.generateQRCode(deviceId)

    } catch (error) {
      await this.handlePairingError(deviceId, error)
      throw error
    }
  }

  // ============================================================================
  // UTILITY METHODS
  // ============================================================================

  /**
   * Get device with validation
   */
  private async getDeviceWithValidation(deviceId: string): Promise<WhatsAppDevice> {
    const device = await prisma.whatsAppDevice.findUnique({
      where: { id: deviceId }
    })

    if (!device) {
      throw new DeviceNotFoundError(deviceId)
    }

    return device
  }

  /**
   * Validate and clean phone number
   */
  private validateAndCleanPhoneNumber(phoneNumber: string): string {
    // Remove all non-digit characters
    const cleaned = phoneNumber.replace(/\D/g, '')
    
    // Validate length (should be between 10-15 digits)
    if (cleaned.length < 10 || cleaned.length > 15) {
      throw new WhatsAppServiceError(
        'Invalid phone number format',
        'INVALID_PHONE_NUMBER'
      )
    }

    // Add country code if missing (assuming international format)
    return cleaned.startsWith('1') ? cleaned : `1${cleaned}`
  }

  /**
   * Generate secure pairing code
   */
  private generateSecurePairingCode(): string {
    // Generate 8-character alphanumeric code
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    let code = ''
    
    for (let i = 0; i < 8; i++) {
      code += chars.charAt(Math.floor(Math.random() * chars.length))
    }
    
    return code
  }

  /**
   * Setup pairing timeout
   */
  private setupPairingTimeout(deviceId: string) {
    // Clear existing timeout
    const existingTimeout = this.activePairingSessions.get(deviceId)
    if (existingTimeout) {
      clearTimeout(existingTimeout)
    }

    // Set new timeout
    const timeout = setTimeout(async () => {
      await this.handlePairingTimeout(deviceId)
    }, this.config.pairingTimeoutMs)

    this.activePairingSessions.set(deviceId, timeout)
  }

  /**
   * Handle pairing timeout
   */
  private async handlePairingTimeout(deviceId: string) {
    try {
      await this.cancelPairing(deviceId)
      console.log(`Pairing timeout for device ${deviceId}`)
    } catch (error) {
      console.error(`Failed to handle pairing timeout for device ${deviceId}:`, error)
    } finally {
      this.activePairingSessions.delete(deviceId)
    }
  }

  /**
   * Clear pairing session
   */
  private async clearPairingSession(deviceId: string) {
    const timeout = this.activePairingSessions.get(deviceId)
    if (timeout) {
      clearTimeout(timeout)
      this.activePairingSessions.delete(deviceId)
    }
  }

  /**
   * Handle pairing errors
   */
  private async handlePairingError(deviceId: string, error: any) {
    try {
      await prisma.whatsAppDevice.update({
        where: { id: deviceId },
        data: {
          status: WhatsAppDeviceStatus.FAILED,
          qrCode: null,
          qrCodeExpires: null
        }
      })
    } catch (dbError) {
      console.error(`Failed to update device status after pairing error:`, dbError)
    }

    await this.clearPairingSession(deviceId)
    console.error(`Pairing error for device ${deviceId}:`, error)
  }

  /**
   * Cleanup all active pairing sessions
   */
  cleanup() {
    for (const [deviceId, timeout] of this.activePairingSessions) {
      clearTimeout(timeout)
    }
    this.activePairingSessions.clear()
  }
}
